ci: adds `build`, `prebuild` and `prepublishOnly` scripts
StuDocu/design-figma-tokens pull request #17
Opened 2022-10-26 07:38 UTC by rmachado-studocu

#### What does this PR do

* Adds `build`, `prebuild` and `prepublishOnly` scripts
* Adds `files` definition to set what goes in the NPM package
* Removes the `postinstall`

Note: I'll generate a prerelease version of 1.0.0 for testing purposes and alignment with `studocu`.

2022-10-26 07:41 UTC, johndalvik approved these changes

2022-10-26 07:53 UTC, midani-studocu approved these changes

2022-10-27 10:40 UTC, midani-studocu requested changes

2022-10-27 10:40 UTC, midani-studocu commented on package.json
> -    "postinstall": "yarn generate:json && yarn generate:scss",
@rmachado-studocu can you rename the script also in the .md files too

2022-10-31 11:19 UTC, midani-studocu approved these changes

2022-11-02 08:51 UTC, merged